/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommanderAppIdRouteImport } from './routes/commander.$appId'
import { Route as CommandeOrderIdRouteImport } from './routes/commande.$orderId'
import { Route as AdminDiagnosticRouteImport } from './routes/admin.diagnostic'
import { Route as AuthenticatedCompteRouteImport } from './routes/_authenticated/compte'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as CommandeSuccesOrderIdRouteImport } from './routes/commande.succes.$orderId'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as AuthenticatedCompteCommandesRouteImport } from './routes/_authenticated/compte.commandes'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicWebhooksSaspayRouteImport } from './routes/api/public/webhooks/saspay'
import { Route as ApiPublicWebhooksNotchpayRouteImport } from './routes/api/public/webhooks/notchpay'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommanderAppIdRoute = CommanderAppIdRouteImport.update({
  id: '/commander/$appId',
  path: '/commander/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeOrderIdRoute = CommandeOrderIdRouteImport.update({
  id: '/commande/$orderId',
  path: '/commande/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDiagnosticRoute = AdminDiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedCompteRoute = AuthenticatedCompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const CommandeSuccesOrderIdRoute = CommandeSuccesOrderIdRouteImport.update({
  id: '/commande/succes/$orderId',
  path: '/commande/succes/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCompteCommandesRoute =
  AuthenticatedCompteCommandesRouteImport.update({
    id: '/commandes',
    path: '/commandes',
    getParentRoute: () => AuthenticatedCompteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksSaspayRoute = ApiPublicWebhooksSaspayRouteImport.update({
  id: '/api/public/webhooks/saspay',
  path: '/api/public/webhooks/saspay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksNotchpayRoute =
  ApiPublicWebhooksNotchpayRouteImport.update({
    id: '/api/public/webhooks/notchpay',
    path: '/api/public/webhooks/notchpay',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/compte': typeof AuthenticatedCompteRouteWithChildren
  '/admin/diagnostic': typeof AdminDiagnosticRoute
  '/commande/$orderId': typeof CommandeOrderIdRoute
  '/commander/$appId': typeof CommanderAppIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/compte/commandes': typeof AuthenticatedCompteCommandesRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/commande/succes/$orderId': typeof CommandeSuccesOrderIdRoute
  '/api/public/webhooks/notchpay': typeof ApiPublicWebhooksNotchpayRoute
  '/api/public/webhooks/saspay': typeof ApiPublicWebhooksSaspayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/compte': typeof AuthenticatedCompteRouteWithChildren
  '/admin/diagnostic': typeof AdminDiagnosticRoute
  '/commande/$orderId': typeof CommandeOrderIdRoute
  '/commander/$appId': typeof CommanderAppIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/compte/commandes': typeof AuthenticatedCompteCommandesRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/commande/succes/$orderId': typeof CommandeSuccesOrderIdRoute
  '/api/public/webhooks/notchpay': typeof ApiPublicWebhooksNotchpayRoute
  '/api/public/webhooks/saspay': typeof ApiPublicWebhooksSaspayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/compte': typeof AuthenticatedCompteRouteWithChildren
  '/admin/diagnostic': typeof AdminDiagnosticRoute
  '/commande/$orderId': typeof CommandeOrderIdRoute
  '/commander/$appId': typeof CommanderAppIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/compte/commandes': typeof AuthenticatedCompteCommandesRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/commande/succes/$orderId': typeof CommandeSuccesOrderIdRoute
  '/api/public/webhooks/notchpay': typeof ApiPublicWebhooksNotchpayRoute
  '/api/public/webhooks/saspay': typeof ApiPublicWebhooksSaspayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/compte'
    | '/admin/diagnostic'
    | '/commande/$orderId'
    | '/commander/$appId'
    | '/.mcp/invoke-tool/$tool'
    | '/compte/commandes'
    | '/api/public/health'
    | '/commande/succes/$orderId'
    | '/api/public/webhooks/notchpay'
    | '/api/public/webhooks/saspay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/compte'
    | '/admin/diagnostic'
    | '/commande/$orderId'
    | '/commander/$appId'
    | '/.mcp/invoke-tool/$tool'
    | '/compte/commandes'
    | '/api/public/health'
    | '/commande/succes/$orderId'
    | '/api/public/webhooks/notchpay'
    | '/api/public/webhooks/saspay'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/compte'
    | '/admin/diagnostic'
    | '/commande/$orderId'
    | '/commander/$appId'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/compte/commandes'
    | '/api/public/health'
    | '/commande/succes/$orderId'
    | '/api/public/webhooks/notchpay'
    | '/api/public/webhooks/saspay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CommandeOrderIdRoute: typeof CommandeOrderIdRoute
  CommanderAppIdRoute: typeof CommanderAppIdRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  CommandeSuccesOrderIdRoute: typeof CommandeSuccesOrderIdRoute
  ApiPublicWebhooksNotchpayRoute: typeof ApiPublicWebhooksNotchpayRoute
  ApiPublicWebhooksSaspayRoute: typeof ApiPublicWebhooksSaspayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commander/$appId': {
      id: '/commander/$appId'
      path: '/commander/$appId'
      fullPath: '/commander/$appId'
      preLoaderRoute: typeof CommanderAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande/$orderId': {
      id: '/commande/$orderId'
      path: '/commande/$orderId'
      fullPath: '/commande/$orderId'
      preLoaderRoute: typeof CommandeOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/diagnostic': {
      id: '/admin/diagnostic'
      path: '/diagnostic'
      fullPath: '/admin/diagnostic'
      preLoaderRoute: typeof AdminDiagnosticRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/compte': {
      id: '/_authenticated/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof AuthenticatedCompteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande/succes/$orderId': {
      id: '/commande/succes/$orderId'
      path: '/commande/succes/$orderId'
      fullPath: '/commande/succes/$orderId'
      preLoaderRoute: typeof CommandeSuccesOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/compte/commandes': {
      id: '/_authenticated/compte/commandes'
      path: '/commandes'
      fullPath: '/compte/commandes'
      preLoaderRoute: typeof AuthenticatedCompteCommandesRouteImport
      parentRoute: typeof AuthenticatedCompteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/saspay': {
      id: '/api/public/webhooks/saspay'
      path: '/api/public/webhooks/saspay'
      fullPath: '/api/public/webhooks/saspay'
      preLoaderRoute: typeof ApiPublicWebhooksSaspayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/notchpay': {
      id: '/api/public/webhooks/notchpay'
      path: '/api/public/webhooks/notchpay'
      fullPath: '/api/public/webhooks/notchpay'
      preLoaderRoute: typeof ApiPublicWebhooksNotchpayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedCompteRouteChildren {
  AuthenticatedCompteCommandesRoute: typeof AuthenticatedCompteCommandesRoute
}

const AuthenticatedCompteRouteChildren: AuthenticatedCompteRouteChildren = {
  AuthenticatedCompteCommandesRoute: AuthenticatedCompteCommandesRoute,
}

const AuthenticatedCompteRouteWithChildren =
  AuthenticatedCompteRoute._addFileChildren(AuthenticatedCompteRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCompteRoute: typeof AuthenticatedCompteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCompteRoute: AuthenticatedCompteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteChildren {
  AdminDiagnosticRoute: typeof AdminDiagnosticRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDiagnosticRoute: AdminDiagnosticRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CommandeOrderIdRoute: CommandeOrderIdRoute,
  CommanderAppIdRoute: CommanderAppIdRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  CommandeSuccesOrderIdRoute: CommandeSuccesOrderIdRoute,
  ApiPublicWebhooksNotchpayRoute: ApiPublicWebhooksNotchpayRoute,
  ApiPublicWebhooksSaspayRoute: ApiPublicWebhooksSaspayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
