/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommanderAppIdRouteImport } from './routes/commander.$appId'
import { Route as CommandeOrderIdRouteImport } from './routes/commande.$orderId'
import { Route as CommandeSuccesOrderIdRouteImport } from './routes/commande.succes.$orderId'
import { Route as ApiPublicWebhooksNotchpayRouteImport } from './routes/api/public/webhooks/notchpay'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommanderAppIdRoute = CommanderAppIdRouteImport.update({
  id: '/commander/$appId',
  path: '/commander/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeOrderIdRoute = CommandeOrderIdRouteImport.update({
  id: '/commande/$orderId',
  path: '/commande/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeSuccesOrderIdRoute = CommandeSuccesOrderIdRouteImport.update({
  id: '/commande/succes/$orderId',
  path: '/commande/succes/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksNotchpayRoute =
  ApiPublicWebhooksNotchpayRouteImport.update({
    id: '/api/public/webhooks/notchpay',
    path: '/api/public/webhooks/notchpay',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/commande/$orderId': typeof CommandeOrderIdRoute
  '/commander/$appId': typeof CommanderAppIdRoute
  '/commande/succes/$orderId': typeof CommandeSuccesOrderIdRoute
  '/api/public/webhooks/notchpay': typeof ApiPublicWebhooksNotchpayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/commande/$orderId': typeof CommandeOrderIdRoute
  '/commander/$appId': typeof CommanderAppIdRoute
  '/commande/succes/$orderId': typeof CommandeSuccesOrderIdRoute
  '/api/public/webhooks/notchpay': typeof ApiPublicWebhooksNotchpayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/commande/$orderId': typeof CommandeOrderIdRoute
  '/commander/$appId': typeof CommanderAppIdRoute
  '/commande/succes/$orderId': typeof CommandeSuccesOrderIdRoute
  '/api/public/webhooks/notchpay': typeof ApiPublicWebhooksNotchpayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/commande/$orderId'
    | '/commander/$appId'
    | '/commande/succes/$orderId'
    | '/api/public/webhooks/notchpay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/commande/$orderId'
    | '/commander/$appId'
    | '/commande/succes/$orderId'
    | '/api/public/webhooks/notchpay'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/commande/$orderId'
    | '/commander/$appId'
    | '/commande/succes/$orderId'
    | '/api/public/webhooks/notchpay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CommandeOrderIdRoute: typeof CommandeOrderIdRoute
  CommanderAppIdRoute: typeof CommanderAppIdRoute
  CommandeSuccesOrderIdRoute: typeof CommandeSuccesOrderIdRoute
  ApiPublicWebhooksNotchpayRoute: typeof ApiPublicWebhooksNotchpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commander/$appId': {
      id: '/commander/$appId'
      path: '/commander/$appId'
      fullPath: '/commander/$appId'
      preLoaderRoute: typeof CommanderAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande/$orderId': {
      id: '/commande/$orderId'
      path: '/commande/$orderId'
      fullPath: '/commande/$orderId'
      preLoaderRoute: typeof CommandeOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande/succes/$orderId': {
      id: '/commande/succes/$orderId'
      path: '/commande/succes/$orderId'
      fullPath: '/commande/succes/$orderId'
      preLoaderRoute: typeof CommandeSuccesOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/notchpay': {
      id: '/api/public/webhooks/notchpay'
      path: '/api/public/webhooks/notchpay'
      fullPath: '/api/public/webhooks/notchpay'
      preLoaderRoute: typeof ApiPublicWebhooksNotchpayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CommandeOrderIdRoute: CommandeOrderIdRoute,
  CommanderAppIdRoute: CommanderAppIdRoute,
  CommandeSuccesOrderIdRoute: CommandeSuccesOrderIdRoute,
  ApiPublicWebhooksNotchpayRoute: ApiPublicWebhooksNotchpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
