/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommanderAppIdRouteImport } from './routes/commander.$appId'
import { Route as CommandeOrderIdRouteImport } from './routes/commande.$orderId'
import { Route as AdminDiagnosticRouteImport } from './routes/admin.diagnostic'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as CommandeSuccesOrderIdRouteImport } from './routes/commande.succes.$orderId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicWebhooksNotchpayRouteImport } from './routes/api/public/webhooks/notchpay'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommanderAppIdRoute = CommanderAppIdRouteImport.update({
  id: '/commander/$appId',
  path: '/commander/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeOrderIdRoute = CommandeOrderIdRouteImport.update({
  id: '/commande/$orderId',
  path: '/commande/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDiagnosticRoute = AdminDiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => AdminRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const CommandeSuccesOrderIdRoute = CommandeSuccesOrderIdRouteImport.update({
  id: '/commande/succes/$orderId',
  path: '/commande/succes/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksNotchpayRoute =
  ApiPublicWebhooksNotchpayRouteImport.update({
    id: '/api/public/webhooks/notchpay',
    path: '/api/public/webhooks/notchpay',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/diagnostic': typeof AdminDiagnosticRoute
  '/commande/$orderId': typeof CommandeOrderIdRoute
  '/commander/$appId': typeof CommanderAppIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/commande/succes/$orderId': typeof CommandeSuccesOrderIdRoute
  '/api/public/webhooks/notchpay': typeof ApiPublicWebhooksNotchpayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/diagnostic': typeof AdminDiagnosticRoute
  '/commande/$orderId': typeof CommandeOrderIdRoute
  '/commander/$appId': typeof CommanderAppIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/commande/succes/$orderId': typeof CommandeSuccesOrderIdRoute
  '/api/public/webhooks/notchpay': typeof ApiPublicWebhooksNotchpayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/diagnostic': typeof AdminDiagnosticRoute
  '/commande/$orderId': typeof CommandeOrderIdRoute
  '/commander/$appId': typeof CommanderAppIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/commande/succes/$orderId': typeof CommandeSuccesOrderIdRoute
  '/api/public/webhooks/notchpay': typeof ApiPublicWebhooksNotchpayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/diagnostic'
    | '/commande/$orderId'
    | '/commander/$appId'
    | '/.mcp/invoke-tool/$tool'
    | '/commande/succes/$orderId'
    | '/api/public/webhooks/notchpay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/diagnostic'
    | '/commande/$orderId'
    | '/commander/$appId'
    | '/.mcp/invoke-tool/$tool'
    | '/commande/succes/$orderId'
    | '/api/public/webhooks/notchpay'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/diagnostic'
    | '/commande/$orderId'
    | '/commander/$appId'
    | '/.mcp/invoke-tool/$tool'
    | '/commande/succes/$orderId'
    | '/api/public/webhooks/notchpay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CommandeOrderIdRoute: typeof CommandeOrderIdRoute
  CommanderAppIdRoute: typeof CommanderAppIdRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  CommandeSuccesOrderIdRoute: typeof CommandeSuccesOrderIdRoute
  ApiPublicWebhooksNotchpayRoute: typeof ApiPublicWebhooksNotchpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commander/$appId': {
      id: '/commander/$appId'
      path: '/commander/$appId'
      fullPath: '/commander/$appId'
      preLoaderRoute: typeof CommanderAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande/$orderId': {
      id: '/commande/$orderId'
      path: '/commande/$orderId'
      fullPath: '/commande/$orderId'
      preLoaderRoute: typeof CommandeOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/diagnostic': {
      id: '/admin/diagnostic'
      path: '/diagnostic'
      fullPath: '/admin/diagnostic'
      preLoaderRoute: typeof AdminDiagnosticRouteImport
      parentRoute: typeof AdminRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande/succes/$orderId': {
      id: '/commande/succes/$orderId'
      path: '/commande/succes/$orderId'
      fullPath: '/commande/succes/$orderId'
      preLoaderRoute: typeof CommandeSuccesOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/notchpay': {
      id: '/api/public/webhooks/notchpay'
      path: '/api/public/webhooks/notchpay'
      fullPath: '/api/public/webhooks/notchpay'
      preLoaderRoute: typeof ApiPublicWebhooksNotchpayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminDiagnosticRoute: typeof AdminDiagnosticRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDiagnosticRoute: AdminDiagnosticRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CommandeOrderIdRoute: CommandeOrderIdRoute,
  CommanderAppIdRoute: CommanderAppIdRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  CommandeSuccesOrderIdRoute: CommandeSuccesOrderIdRoute,
  ApiPublicWebhooksNotchpayRoute: ApiPublicWebhooksNotchpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
